@echo off

set SEASON=%1
set TGT_BASE_DIR=C:\dev\del_stats\frontend\data
set TGT_EXTENDED_DIR=C:\dev\del_stats\frontend\data\

set DEL_DATA_BASE_DIR=c:\del

if [%SEASON%] EQU [] (
    set SEASON=2020
)

echo %SEASON%

echo + Copying %SEASON% stats:
echo + Copying full register of all players...
copy data\del_players.json %TGT_BASE_DIR%
echo + Copying personal data of all players...
copy data\%SEASON%\del_player_personal_data.json %TGT_BASE_DIR%\%SEASON%
echo + Copying league-wide stats file...
copy data\%SEASON%\del_league_stats.json %TGT_BASE_DIR%\%SEASON%
echo + Copying goalie and skater stats...
copy data\%SEASON%\del_goalie_game_stats.json %TGT_BASE_DIR%\%SEASON%
copy data\%SEASON%\del_player_game_stats_aggregated.* %TGT_BASE_DIR%\%SEASON%
copy data\%SEASON%\del_player_game_stats.csv %TGT_BASE_DIR%\%SEASON%
echo + Copying team stats...
copy data\%SEASON%\del_team_game_stats.json %TGT_BASE_DIR%\%SEASON%
echo + Copying scoring streaks...
copy data\%SEASON%\del_streaks_strict.json %TGT_BASE_DIR%\%SEASON%
copy data\%SEASON%\del_streaks_loose.json %TGT_BASE_DIR%\%SEASON%
echo + Copying scoring slumps...
copy data\%SEASON%\del_slumps_strict.json %TGT_BASE_DIR%\%SEASON%
copy data\%SEASON%\del_slumps_loose.json %TGT_BASE_DIR%\%SEASON%
echo + Copyting shots data...
copy data\%SEASON%\del_shots.csv %TGT_BASE_DIR%\%SEASON%
echo + Copying modified per-player stats...
xcopy /i /y /d data\%SEASON%\per_player %TGT_BASE_DIR%\%SEASON%\per_player

echo + Copying career stats:
echo + Copying full career stats file...
copy data\career_stats\updated_career_stats.json %TGT_BASE_DIR%\career_stats\career_stats.json
echo + Copying modified per-player career stats...
xcopy /i /y /d data\career_stats\per_player %TGT_BASE_DIR%\career_stats\per_player
echo + Copying modified per-team career stats...
xcopy /i /y /d data\career_stats\per_team %TGT_BASE_DIR%\career_stats\per_team

:: Daten für Extended-Version
echo + Copying data for extended version:
echo + Copying full register of all players...
copy data\del_players.json %TGT_EXTENDED_DIR%
echo + Copying personal data of all players...
copy data\%SEASON%\del_player_personal_data.json %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying game facts...
copy %DEL_DATA_BASE_DIR%\del_facts\facts.json %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying full schedule...
copy data\%SEASON%\full_schedule.json %TGT_EXTENDED_DIR%\%SEASON%
if [%SEASON%] EQU [2020] (
    echo + Copying calendar file...
    copy data\%SEASON%\del_calendar.ics %TGT_BASE_DIR%
)
echo + Copying coaches records...
copy data\%SEASON%\coaches.json %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying head-to-head records...
copy data\%SEASON%\h2h.json %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying league-wide stats file...
copy data\%SEASON%\del_league_stats.json %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying goalie stats...
copy data\%SEASON%\del_goalie_game_stats.json %TGT_EXTENDED_DIR%\%SEASON%
copy data\%SEASON%\del_goalie_game_stats_aggregated.json %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying skater stats...
copy data\%SEASON%\del_player_game_stats_aggregated.* %TGT_EXTENDED_DIR%\%SEASON%
copy data\%SEASON%\del_player_game_stats.csv %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying team stats...
copy data\%SEASON%\del_team_game_stats.json %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying scoring streaks...
copy data\%SEASON%\del_streaks_strict.json %TGT_EXTENDED_DIR%\%SEASON%
copy data\%SEASON%\del_streaks_loose.json %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying scoring slumps...
copy data\%SEASON%\del_slumps_strict.json %TGT_EXTENDED_DIR%\%SEASON%
copy data\%SEASON%\del_slumps_loose.json %TGT_EXTENDED_DIR%\%SEASON%
echo + Copying modified per-player stats...
xcopy /i /y /d data\%SEASON%\per_player %TGT_EXTENDED_DIR%\%SEASON%\per_player

echo + Copying career stats for extended version:
echo + Copying full career stats file...
copy data\career_stats\updated_career_stats.json %TGT_EXTENDED_DIR%\career_stats\career_stats.json
echo + Copying modified per-player career stats...
xcopy /i /y /d data\career_stats\per_player %TGT_EXTENDED_DIR%\career_stats\per_player
echo + Copying modified per-team career stats...
xcopy /i /y /d data\career_stats\per_team %TGT_EXTENDED_DIR%\career_stats\per_team
